#Path to load default configs from, intended for setting global server configs for newly created worlds, but also works when recreating client and common configs.
defaultConfigsPath = "defaultconfigs"
#When single config values need to be corrected (think like the config value is a number 1-10, but the user enters an incompatible input like '5.0', in that case only this single value needs fixing not the whole file),
#Forge restores the built-in default value for that option, but ignores a value that is set in a possibly present default config in 'defaultconfigs'.
#This option fixes this behavior and checks for a value in a default config from 'defaultconfigs' before falling back to the built-in default.
correctConfigValuesFromDefaultConfig = true
#Disables File Watcher. Used to automatically update config if its file has been modified.
disableConfigWatcher = false
