name: Report A Bug
description: >-
  Only Minecraft versions listed on the main branch are supported. Support may additionally vary based on the severity of an issue.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Fuzss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader (Required)
      description: What mod loader are you using to play the mod?
      multiple: false
      options:
        - "⸺"
        - "Fabric"
        - "NeoForge"
        - "Forge"
        - "Quilt"
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft Version(s) (Required)
      description: What Minecraft version(s) are you using the play the mod?
      placeholder: ex. 1.20.1
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version(s) (Required)
      description: What mod version(s) are you using to play?
      placeholder: ex. v8.0.0
    validations:
      required: true
  - type: dropdown
    id: mods
    attributes:
      label: Minimal Setup (Required)
      description: Can your issue be reproduced with a minimal set of mods (only this mod + dependencies)?
      multiple: false
      options:
        - "⸺"
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes (Required)
      description: Please explain what happens because of the issue (including all the steps required to cause it), and what behavior you would expect if the issue were fixed.
      placeholder: >-
        ex.  
        
        Current behavior: Shift-clicking a fuel item in the furnace fuel slots does not work.

        Steps to reproduce: 
        
        1. Open the furnace screen.

        2. Attempt to shift-click a fuel item into the fuel slot.
        
        Expected: Following the steps to reproduce the bug, the fuel item should be moved into the furnace fuel slot.
    validations:
      required: true
  - type: input
    id: latest-log
    attributes:
      label: latest.log (Required)
      description: Please paste the url to your shared `latest.log` file. Note that issue reports without this file are difficult to solve and unlikely to be processed. [To share your `latest.log` here, please follow these steps.](https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285)
      placeholder: ex. https://gist.github.com/<your_user_name>/<gist_id>
    validations:
      required: true
