blank_issues_enabled: false
contact_links:
  - name: Ask A Question
    url: https://lunapixel.studio/discord
    about: "Join the Luna Pixel Studios Discord Server in the #fuzs-projects channel for additional support."