name: Submit A Crash Report
description: >-
  Only Minecraft versions listed on the main branch are supported. Support may additionally vary based on the severity of an issue.
title: "[Crash]: "
labels: ["bug", "high priority"]
assignees:
  - Fuzss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader (Required)
      description: What mod loader are you using to play the mod?
      multiple: false
      options:
        - "⸺"
        - "Fabric"
        - "NeoForge"
        - "Forge"
        - "Quilt"
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft Version(s) (Required)
      description: What Minecraft version(s) are you using the play the mod?
      placeholder: ex. 1.20.1
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version(s) (Required)
      description: What mod version(s) are you using to play?
      placeholder: ex. v8.0.0
    validations:
      required: true
  - type: dropdown
    id: mods
    attributes:
      label: Minimal Setup
      description: Can your issue be reproduced with a minimal set of mods (only this mod + dependencies)?
      multiple: false
      options:
        - "⸺"
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes (Required)
      description: Please explain which steps we need to do to reproduce the issue. Please include anything else you'd like to say about it.
      placeholder: >-
        ex.  
        
        1. Open the furnace screen.

        2. Shift-click a fuel item into the fuel slot.

        3. The game crashes.
    validations:
      required: true
  - type: input
    id: crash-report
    attributes:
      label: Crash Report (Required)
      description: >-
        Please paste the url to your shared crash report. Note that issue reports without this file are difficult to solve and unlikely to be processed. [To share your crash report here, please follow these steps.](https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b)
      placeholder: ex. https://gist.github.com/<your_user_name>/<gist_id>
    validations:
      required: true
  - type: input
    id: latest-log
    attributes:
      label: latest.log (Optional)
      description: Please paste the url to your shared `latest.log` file. [To share your `latest.log` here, please follow these steps.](https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285)
      placeholder: ex. https://gist.github.com/<your_user_name>/<gist_id>
